### ISSUE TITLE
PC floppy troubles

### ISSUE THREAD

**Issue by f-bone** [RetroNynjah/Amiga-External-Floppy-Adapter#1]
Hi,

I tried with a modded for Amiga ALPS floppy but it doesn't work. I actually think I burned something on the floppy (as now it won't work as standalone inside the Amiga - used to) and also fried R5.

What I want to do is to print a case and create a df1 floppy that can be used to copy disks to the internal Amiga floppy.

Any ideas?

**Comment by RetroNynjah** [comment]
I don't know anything about modded for Amiga ALPS floppies but it should be quite hard to fry R5 since it's a 12k pull-up resistor. Even if that resistor was connected directly between +5V and GND the resistance would be too high to allow any noticable current flow.

Is it possible that you reversed the power connector?
That would kill the floppy drive.

**Comment by f-bone** [comment]
its possible I reversed the connection or went a pin to the right, I now replaced the resistor and have the following behavious (btw a modded ALPS or whatever brand is enabling it to work with Amigas - normal PC floppies wouldn't otherwise):

1) using your adapter and gotek works either externally (but no internal floppy connected) or as standalone internally
2) adapter + gotek + internal floppy, the gotek as df0 works using a boot switch for df0/df1 but when the gotek is set as df1 the internal now df0 floppy wont read disks, this configuration would also allow to copy disks from gotek to floppies but does not work
3) adapter+floppy does not work at all - this was my main wish to build an external floppy and use it in conjunction with the internal floppy.. if that worked I would opt for a df2 floppy so with 3 floppies connected I could play a 3-floppy game without swapping disks like we did back in the day

I hope Im not wasting your time - maybe someone else can verify my findings so that I know Im not missing something or going crazy :D

**Comment by RetroNynjah** [comment]
It's been a couple of years since I designed this and I was unsure whether I tested external 3.5" floppy or not back then since all I needed it for initially was an external Gotek (I already have external floppy drives).
I just tested it with internal Gotek together with an external Floppy and I can read from both the drives.
I don't have a DF0/DF1 switch so I can't test that thing though.

If an external Gotek works fine with the adapter but an external floppy does not work with the adapter then it sounds like you are either lacking 12V supply from the disk drive port (pin 23) or maybe you are using some non TTL level logic ICs (IC1/IC2) that aren't using the right levels for the drive interface and that the Gotek maybe is more forgiving about the levels than the floppy drive.
First measure the 12V level on the floppy connector on the adapter. This is the pin assignments for the power connector:

![image](https://user-images.githubusercontent.com/59034596/160259182-fcffbf97-d0d0-4fa7-90b3-82afc7b240a1.png)

What's the part number of the logic chips you are using? The one I tested with is using 74HCT chips for both IC1 and IC2 but it is designed for 74LS chips so any of those should probably be ok while 74HC and some other variants might not work.

**Comment by f-bone** [comment]
Hi thanks for your input!

I tried again today but to no avail. When both drivers are connected (floppy internally, gotek externally) the system gets confused. It even shows 4 drives available in xcopy as shown in picture. Also the normal floppy won't work externally at all. The gotek when standalone works externally in this new test.

![65292811-E5AC-4F74-A006-0093B59C2C5C](https://user-images.githubusercontent.com/16945397/160431517-cef307ec-bcf1-4052-9906-321f6ac51f88.jpeg)

**Comment by RetroNynjah** [comment]
Did you verify that the external disk receives 12V?

**Comment by f-bone** [comment]
yes I did.. infact my test bed A1200 had a bad trace from and old S/C which I found out today and repaired (https://www.facebook.com/RetroLabAthens/ we know our way around a little bit!) but my A500+ test bed was ok all along with 12V present... I was hoping we could modify your design even using jumpers or cut traces on current PCB and do further testing. I am not good at designing things - I am ok with repairing them..

**Comment by RetroNynjah** [comment]
I can't reproduce your problems. That's why I asked what partnunbers you used for the chips. If yours are different from mine then that could be somethingfor me to try.
I tried copying a disk using X-Copy the other day. I copied from internal Gotek to external 3.5" and it worked fine. I have now tried from internal 3.5" to external 3.5" and that works too except for some verify errors that is most likely caused by a wonky drive.
Here's a video from X-Copy and the two 3.5" drives. I hope you can see it. My computer doesn't show any confusion about the drives.

https://user-images.githubusercontent.com/59034596/160442835-a9961815-fc35-4c4b-aacc-a94074833e07.mp4

**Comment by RetroNynjah** [comment]
I have reproduced you problem now but with a later revision of my board. I made a Rev 2 that I never tested and therefore never published. I built it now and the Rev 2 didn't work. It detects four drives just as you described.

The Rev 1 gerbers that were on github doesn't seem to be the exact same version as the Rev 1 PCB I was testing with. The silkscreen is different and I thought that was the only update I did before publishing but something else must have happened to the PCB between my version and the one that I published.
It will take me some time to figure out what happened to it so that I can repair it and repair my Rev 2. It's possible that it's an error that can be patched but meanwhile I have replaced the gerbers on Github with the version that I have tested and that works.
I'm really sorry about these problems. I can send you a couple of boards of the older version that works for me if you want them.

**Comment by f-bone** [comment]
Thank you for spending time on this! I'm glad that at least you did reproduce the issue so we can fix it! I hope it's possible to patch current boards as I made 3pcs with db23 and these don't come by easy ☺️☺️☺️ and still have a couple of spare boards.. if you're in Europe then maybe sending me a board or two would be nice. I'll pay for shipping.

**Comment by RetroNynjah** [comment]
Can I reach you at the repairlab address on your facebook page?

**Comment by f-bone** [comment]
Sure!

**Comment by RetroNynjah** [comment]
The issue I was having when reproducing the problem was a floppy drive problem. I still can't reproduce the problem using good working floppies or Goteks.
I have restored the updated Rev 1 gerbers again since they don't seem to be the issue.

I will also upload my Rev 2 gerbers later which I have finally tested now after a couple of years :)
The Rev 2 changes are mostly cosmetic. The power connector is rotated so that it's possible to install a right-angle connector which makes it possible to use a power connector on the board even when mounting in an enclosure.

**Comment by f-bone** [comment]
thank you for all your efforts! I guess the ball is now in my court! --I will keep testing it (I have rev2 only at the moment) using new ICs too - will try HCT instead of LS.

**Comment by RetroNynjah** [comment]
The Revision you have should be Rev 1 too but the final version of Rev 1.
The one I had was a preview of Rev 1 which didn't have all the silkscreen added yet. There were no other differences that I could see except for silkscreen. You should have the earlier Rev 1 in your mail in a few days if you want to test it.

I have finally tested the chaining of extra external drives connected through my floppy adapter. This should have been tested years ago.
Gotek or floppy on floppy interface J2 on the floppy adapter should be DF1 when floppy adapter is connected directly to Amiga external drive port.
Other external floppy connected through J4 on floppy adapter should then become DF2.
Unfortunately that doesn't seem to work correctly so I'm currently trying to find out what's wrong. I will maybe have to create another revision to fix that before I publish anything more.

**Comment by f-bone** [comment]
Nice! Also thank you for sending the boards will report back on any findings I have after further testing. 🙏

**Comment by RetroNynjah** [comment]
I have identified the problem with chaining/passthrough.

The NAND gates need to be of open collector type for this to work properly so replace the 74LS00 with a 74LS38 and it should work fine. No design changes needed except for component value on the silk screen and in the schematics.
With a 74LS00 the floppy adapter works together with other external floppies but not with other floppy adapters based on 74LS00's.
With a 74LS38 it works together with other floppy adapters too.
I have tested the following combinations with two of my floppy adapters:
|DF1|DF2|
|-----|-----|
|Floppy|Floppy|
|Floppy|Gotek|
|Gotek|Floppy|
|Gotek|Gotek|

I have copied disks from DF1 to DF2 and the other way around using X-Copy.
I have also tried to chain my adapters before and after other types of external floppies. For example running my adapters as DF2 and DF3.
I can't find any more chaining issues after switching to 74LS38 and I don't know what else to test so I will update the schematics and gerbers and release a new revision (Rev 3) with mostly informational changes (schematis and silkscreen).

If you can find a 74LS38 you may want to try if that helps with your problems but I doubt it will make any difference since my adapters worked fine with 74LS00 too, just not with multiple 74LS00 based adapters in the chain.

**Comment by RetroNynjah** [comment]
I also found some 74HCT03's and some 74F38's and they seems to work fine as well.

**Comment by f-bone** [comment]
thats great news. have you also identified the cause of showing 4 floppies in xcopy at some point (also in A1200 boot menu when pressing two mouse buttons at boot)?

**Comment by RetroNynjah** [comment]
I have not seen the issue with four drives again. I saw it only once and it seems to have been related to a flaky floppy drive.

**Comment by f-bone** [comment]
that means my drive had a similiar issue then!.. Ill get back to testing.. thank you 💯
